#!/usr/bin/env bash
#displays Best School 10 times, but for the 9th iteration,displays Best

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Best School"
		echo -e "\nHi"

	else
		echo "Best School"
	fi

	((i++))
done
