#!/usr/bin/env bash

# Variables
facebook='8.8.8.8 facebook.com'
hosts=/etc/hosts
backup=~/hosts.bak
new_hosts=~/hosts.new

# Backup the original hosts file
cp $hosts $backup

# Create a new hosts file with the required changes
cp $hosts $new_hosts
sed -i 's/127.0.0.1/127.0.0.2/' $new_hosts
echo "$facebook" >> $new_hosts

# Overwrite the original hosts file with the new one
sudo cp -f $new_hosts $hosts

# Display the updated hosts file
echo "Updated /etc/hosts:"
cat $hosts

