#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/g' /etc/nginx/sites-available/default

sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

sudo service nginx restart

ps auxff | grep ngin[x]
nc -z 0 8080
